### ISSUE TITLE
Right-clicking during play mode hangs Unity

### ISSUE THREAD

**Issue by partlyhuman** [MatiM36/ContextClickUnityTool#1]
The check of `EditorApplication.isPlaying` on the static constructor doesn't handle changes to the play state during an editor session, so if the intent was to ignore context menu clicks in play mode, the `if (EditorApplication.isPlaying) return;` early exit should probably be added to `OnSceneGUI()`.

**Comment by MatiM36** [comment]
Can you tell me in which version of Unity you had this issue? I tried and i cannot reproduce the problem.

**Comment by partlyhuman** [comment]
Hehe who knows any more... I'll close this 😄
